quarkus:
  datasource:
    username: progressive
    password: delivery
    jdbc:
      url: jdbc:h2:mem:test;DB_CLOSE_ON_EXIT=FALSE
      driver: org.h2.Driver

  hibernate-orm:
    database:
      generation: drop-and-create
    dialect: org.hibernate.dialect.H2Dialect

  smallrye-openapi:
    enable: true
