quarkus:
  http:
    auth:
      basic=true:
    access-log:
      enabled: true
    limits:
      max-form-attribute-size: 10000
    body:
      handle-file-uploads: true
      delete-uploaded-files-on-end: true
  log:
    category:
      "io.quarkus.http.access-log":
        level: INFO

  smallrye-openapi:
    enable: true

  datasource:
    username: progressive
    password: delivery
    jdbc:
      url: jdbc:h2:mem:test;DB_CLOSE_ON_EXIT=FALSE
      driver: org.h2.Driver

  hibernate-orm:
    database:
      generation: drop-and-create
    dialect: org.hibernate.dialect.H2Dialect
